# Generated by Django 4.2.4 on 2023-10-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='related_officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('officer', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
    ]
