# Generated by Django 4.2.4 on 2023-10-16 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='related_officer',
        ),
    ]
