# Generated by Django 4.2.4 on 2023-12-02 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_mychats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
