# Generated by Django 4.2.7 on 2023-12-03 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mychats',
            name='frnd',
        ),
        migrations.RemoveField(
            model_name='mychats',
            name='me',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Mychats',
        ),
    ]
