# Generated by Django 4.2.4 on 2023-11-04 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='nameofcity',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='name',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='name',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='height',
            old_name='name',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='hobbies',
            old_name='name',
            new_name='nameofhobbie',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='name',
            new_name='range',
        ),
        migrations.RenameField(
            model_name='medical_condition',
            old_name='name',
            new_name='medical_condition',
        ),
        migrations.RenameField(
            model_name='qualification',
            old_name='name',
            new_name='nameofQualification',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='name',
            new_name='nameofwork',
        ),
    ]
