# Generated by Django 4.2.4 on 2023-10-23 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerfor', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('lookingfor', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('marrital_status', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('height', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('Qualification', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('work', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('experience', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('hobbies', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('income', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('medical_condition', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('related_officer', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('username', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_mail_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp', models.ImageField(upload_to='dp')),
                ('username', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='family_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('father_education', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('father_occupation', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('mother_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('mother_education', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('mother_occupation', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('sister', models.TextField(blank=True, null=True)),
                ('brother', models.TextField(blank=True, null=True)),
                ('native_place', models.TextField(blank=True, null=True)),
                ('relatives', models.TextField(blank=True, null=True)),
                ('username', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
