# Generated by Django 4.2.4 on 2023-10-25 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='user',
        ),
    ]
