# Generated by Django 4.2.4 on 2023-11-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_profile_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Qualification',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hobbies',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
