# Generated by Django 4.2.7 on 2023-12-31 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0013_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='status',
            field=models.CharField(blank=True, choices=[('Requested', 'Requested'), ('Followed', 'Followed'), ('Unfollowed', 'Unfollowed')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='ufrom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ufrom', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follow',
            name='uto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uto', to=settings.AUTH_USER_MODEL),
        ),
    ]
