# Generated by Django 4.2.4 on 2023-10-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_delete_city_delete_qualification_delete_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lookingfor',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='registerfor',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
