# Generated by Django 4.2.7 on 2024-01-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_follow_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='status',
            field=models.CharField(blank=True, choices=[('Requested', 'Requested'), ('Followed', 'Followed'), ('Rejected', 'Rejected'), ('Unfollowed', 'Unfollowed')], max_length=50, null=True),
        ),
    ]
