# Generated by Django 4.2.4 on 2023-10-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_remove_profile_age_alter_profile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='related_officer',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
