# Generated by Django 4.2.7 on 2024-04-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reginal_manager',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
