# Generated by Django 4.2.4 on 2023-10-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AddField(
            model_name='user',
            name='relatedo_fficer',
            field=models.CharField(default='', max_length=50),
        ),
    ]
