# Generated by Django 4.2.4 on 2023-10-16 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_remove_user_gender_user_relatedo_fficer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
