# Generated by Django 4.2.7 on 2024-04-04 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0019_user_level_reginal_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_level',
            name='reginal_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reginal_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
