# Generated by Django 4.2.7 on 2024-04-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_user_level_reginal_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_level',
            name='access_type',
            field=models.CharField(choices=[('admin', 'admin'), ('reginal_manager', 'reginal_manager'), ('officer', 'officer'), ('user', 'user')], default='user', max_length=50),
        ),
    ]
