# Generated by Django 4.2.7 on 2024-04-13 18:00

from django.db import migrations
import prefix_id.field


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_reginal_manager_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reginal_manager_profile',
            name='id',
        ),
        migrations.AddField(
            model_name='reginal_manager_profile',
            name='reginal_manager_id',
            field=prefix_id.field.PrefixIDField(default=12, editable=False, max_length=26, prefix='RGM', primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
